### ISSUE TITLE
Build issue - ubuntu 18.04

### ISSUE THREAD

**Issue by efigueroa** [jonathanballs/logmaster#1]
Haven't used D before but this project looked interesting to me. I ran 

`apt install dub`

and 

`dub build `

and get the following: 

```
> dub build                                                                      130 master?
Performing "debug" build using /usr/bin/ldc2 for x86_64.
gtk-d:gtkd 3.8.5: target for configuration "library" is up to date.
gtk-d:gstreamer 3.8.5: target for configuration "library" is up to date.
gtk-d:peas 3.8.5: target for configuration "library" is up to date.
gtk-d:sv 3.8.5: target for configuration "library" is up to date.
gtk-d:vte 3.8.5: target for configuration "library" is up to date.
logmaster ~master: building configuration "application"...
source/logmaster/backends/file.d(105,68): Error: function std.range.slide!(cast(Flag)true, ulong[]).slide is not accessible from module file
/usr/bin/ldc2 failed with exit code 1.
```

**Comment by efigueroa** [comment]
more info:
```
> dub --version
DUB version 1.8.0-2, built on Mar 27 2018
```

**Comment by jonathanballs** [comment]
Interesting. I am using dub version 1.13 (which was released last month rather than last year. You can see on line 103 [that `slide()` is clearly imported](https://github.com/jonathanballs/logmaster/blob/master/source/logmaster/backends/file.d#L103) so I'm thinking that perhaps the std library was updated during this time.

Would you be able to try getting the latest version of dub for your platform and trying again it to see if that fixes it. I will update the Readme to reflect this if so.

**Comment by jonathanballs** [comment]
I will be setting up packages for Ubuntu and Arch Linux soon. These will be precompiled and much easier to use than compiling yourself anyway.

**Comment by efigueroa** [comment]
Used Jordi Sayol's D-Apt repo and installed DUB version 1.13.0. I was able to build logmaster successfully.

**Comment by jonathanballs** [comment]
Excellent. Please let me know what you think/if there are any features you would like.
